x                   = "❌"
white_check_mark    = "✅"
eye                 = "👁"
zzz                 = "💤"
thumbs_up           = "👍"
hourglass           = "⌛"
robot               = "🤖"
trashcan            = "🗑️"